<a href="https://colab.research.google.com/github/krishjaiswal27/Nifty50-Exploratory-Data-Analysis/blob/main/Nifty50_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os, glob
import pandas as pd

In [6]:
files = glob.glob('/content/drive/MyDrive/eda/nifty50_data/**/*.csv', recursive=True)
print(f"Found {len(files)} CSV files")
print(files[:5])

Found 50 CSV files
['/content/drive/MyDrive/eda/nifty50_data/ICICIBANK.csv', '/content/drive/MyDrive/eda/nifty50_data/DIVISLAB.csv', '/content/drive/MyDrive/eda/nifty50_data/NTPC.csv', '/content/drive/MyDrive/eda/nifty50_data/LT.csv', '/content/drive/MyDrive/eda/nifty50_data/ADANIPORTS.csv']

In [7]:
sample = pd.read_csv(files[0])
print(sample.columns.tolist())
sample.head()

['Price', 'Close', 'High', 'Low', 'Open', 'Volume']

,Price,Close,High,Low,Open,Volume
0,Ticker,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2026-05-18,1251.0999755859375,1253.699951171875,1232.0,1235.5,13918850
3,2026-05-19,1240.800048828125,1256.300048828125,1229.800048828125,1251.0999755859375,38929053
4,2026-05-20,1237.300048828125,1239.699951171875,1223.300048828125,1230.0,14953103

In [8]:
all_dfs = []
for filepath in files:
  symbol = os.path.splitext(os.path.basename(filepath))[0]
  temp_df = pd.read_csv(filepath)
  temp_df['symbol'] = symbol
  all_dfs.append(temp_df)

df = pd.concat(all_dfs, ignore_index=True)
print(df.shape)
df.head()

(1154, 8)

,Price,Close,High,Low,Open,Volume,symbol,Adj Close
0,Ticker,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK,NaN
1,Date,NaN,NaN,NaN,NaN,NaN,ICICIBANK,NaN
2,2026-05-18,1251.0999755859375,1253.699951171875,1232.0,1235.5,13918850,ICICIBANK,NaN
3,2026-05-19,1240.800048828125,1256.300048828125,1229.800048828125,1251.0999755859375,38929053,ICICIBANK,NaN
4,2026-05-20,1237.300048828125,1239.699951171875,1223.300048828125,1230.0,14953103,ICICIBANK,NaN